using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Dojo.Domain.Entities;

namespace Dojo.Infrastructure
{
    public class DojoContext : DbContext
    {
        public DojoContext (DbContextOptions<DojoContext> options) : base(options)
        {
        }

        public DbSet<Arme> Arme { get; set; } = default!;

        public DbSet<Samourai> Samourai { get; set; } = default!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            int idSamourai = 1;
            int idArme = 1;
            int idArtMartial = 1;
            Random r = new Random();

            // Arts martiaux
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Krav Maga" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Keysi Fighting Method" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Jiu-Jitsu Brésilien" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Judo" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Muay Thai" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Taekwondo" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Jujutsu japonais" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Aïkido" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Boxe" });
            modelBuilder.Entity<ArtMartial>().HasData(new ArtMartial { Id = idArtMartial++, Name = "Karaté" });

            // Armes
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Katana", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Yumi", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Wakisashi", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Naginata", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Yari", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Masakari", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Nodachi", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Tessen", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Tachi", Damage = r.Next(500) });
            modelBuilder.Entity<Arme>().HasData(new Arme { Id = idArme++, Name = "Shuriken", Damage = r.Next(500) });

            // Samourais
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Abe Masakatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Adachi Yasumori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Adachi Kagemori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Adams William", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Aiou Mototsuna", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Akai Terukage", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Akao Kiyotsuna", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Akechi Mitsuhide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Akiyama Nobutomo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Amago Haruhisa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Amago Yoshihisa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Andō Morinari", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ankokuji Ekei", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Aochi Shigetsuna", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Aokage Takaakira", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Aoki Kazushige", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Akahori Chohichi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Arai Hakuseki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Araki Motokiyo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Araki Murashige", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Araki Muratsugu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Arima Kihei", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Asakura Yoshikage", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ayame Kagekatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Azai Hisamasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Azai Nagamasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Azai Sukemasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Baba Nobufusa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Bessho Nagaharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Chacha", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Chiba Shusaku Narimasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Chōsokabe Morichika", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Chōsokabe Kunichika", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Chōsokabe Motochika", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Chōsokabe Nobuchika", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Collache Eugène", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Date Masamune", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Date Shigezane", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Doi Toshikatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Etō Shinpei", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Endō Naotsune", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Enjoji Nobutane", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Enomoto Takeaki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Era Fusahide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Fūma Kotarō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Fuwa Mitsuharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Fukushima Masanori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Gamō Katahide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Gamō Ujisato", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Harada Naomasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Harada Nobutane", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Harada Sanosuke", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hasekura Tsunenaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hattori Hanzō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hatano Hideharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hasegawa Eishin", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hayashizaki Jinsuke Shigenobu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hayashi Narinaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hijikata Toshizo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hirate Masahide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hitotsubashi Keiki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hōjō Masako", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hōjō Tokimune", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hōjō Ujiyasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hōjō Ujimasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Honda Tadakatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Honda Tadatomo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Honganji Kennyo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Horio Yoshiharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hosokawa Fujitaka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hosokawa Gracia", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hosokawa Tadaoki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Hotta Masatoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naoaki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naomasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naomori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naonaka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naosuke", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naotaka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naotora", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naoyuki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ii Naozumi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Iizasa Ienao", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ijuin Tadaaki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ikeda Tsuneoki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Imagawa Ujizane", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Imagawa Yoshimoto", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Imai Kanehira", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Inaba Yoshimichi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Inugami Nagayasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ishida Mitsunari", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Isshiki Fujinaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Itagaki Nobukata", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Itō Hirobumi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Iwanari Tomomichi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Jinbo Nagamoto", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Jonas Tönse", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kannan Kumar(Salem)", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kakeda Toshimune", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kaneko Ietada", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Katagiri Katsumoto", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Katakura Kojūro", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Katakura Shigenaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kataoka Mitsumasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Katō Kiyomasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kawakami Gensai", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kido Takayoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kikkawa Hiroie", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kimotsuki Kanetsugu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kitamura Kansuke", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kobayakawa Hideaki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kobayakawa Hidekane", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kobayakawa Takakage", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Konishi Yukinaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kojima Toyoharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kuroda Kanbei", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kuroda Kiyotaka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kusunoki Masashige", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kuwana Tarozaemon", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Kumagai Naozane", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Maeda Keiji", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Maeda Matsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Maeda Nagatane", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Maeda Toshiie", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Maeda Toshinaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Maeda Toshitsune", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Magome Kageyu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Manabe Akifusa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsudaira Katamori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsudaira Nobutsuna", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsudaira Nobuyasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsudaira Higo no Kami Katamori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsudaira Sadanobu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsudaira Tadayoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsudaira Teru", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsunaga Hisahide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsunaga Hisamichi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsuo Bashō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Matsudaira Motoyasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Mitsunaka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Yoshiie", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Yoshimitsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Yoshinaka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Yoshitomo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Yoshitsune", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Tameyoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Yorimasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Yorimitsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Yoritomo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minamoto no Noriyori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Minoro Takashi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miura Anjin", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miura Yoshimoto", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miyamoto Musashi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miyoshi Chōkei", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miyoshi Kazuhide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miyoshi Masaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miyoshi Masayasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miyoshi Moriyata", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miyoshi Nagayuki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Miyoshi Yoshitsugu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mizuno Tadakuni", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Moniwa Yoshinao", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mōri Motonari", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mōri Nagasada", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mori Nagayoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mōri Okimoto", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mori Ranmaru", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mōri Takamoto", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mori Tadamasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mōri Terumoto", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Mori Yoshinari", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Murai Sadakatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nagakura Shinpachi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nagao Harukage", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nagao Kagenobu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nagao Masakage", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nagao Tamekage", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nakagawa Kiyohide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nakaoka Shintarō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Naoe Kagetsuna", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Naoe Kanetsugu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Narita Kaihime", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nene", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Nihonmatsu Yoshitsugu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Niimi Nishiki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Niiro Tadamoto", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Niwa Nagahide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Niwa Nagashige", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Hiroyoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Nobuhide", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Nobukata", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Nobukiyo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Nobunaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Nobutada", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Nobutomo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Nobukatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Oda Nobuyasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ogasawara Shōsai", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ōishi Kuranosuke", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Okada Izō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Judge Ooka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ōta Dōkan", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ōtani Yoshitsugu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ōtani Yoshiharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ōtomo Sōrin", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Okita Sōji", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ōkubo Toshimichi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Okunomiya Masaie", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ōuchi Yoshitaka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Omy Yoshika", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Pore Sufi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Reizei Takatoyo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Rokkaku Sadayori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Rokkaku Yoshiharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Rokkaku Yoshikata", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Rusu Masakage", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ryūzōji Takanobu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Saigo Kiyokazu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Saigō Masako", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sagara Taketō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Saigō Takamori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Saigo Yoshikatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Saitō Dōsan", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Saitō Hajime", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Saito Musashibō Benkei", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Saitō Yoshitatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sakai Tadakiyo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sakai Tadashige", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sakai Tadatsugu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sakai Tadayo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sakakibara Yasumasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sakamoto Ryōma", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sakuma Morimasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sakuma Nobumori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sanada Akihime", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sanada Komatsuhime", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sanada Masayuki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sanada Nobuyuki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sanada Yukimura", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sasaki Kojirō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sassa Narimasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sasuke Sarutobi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Serizawa Kamo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shibata Katsuie", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shima Sakon", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimada Ichirō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimazu Katsuhisa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimazu Tadahisa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimazu Tadatsune", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimazu Tadayoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimazu Takahisa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimazu Toyohisa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimazu Yoshihiro", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shimazu Yoshihisa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Shindou Hiroshii", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sogo Nagayasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Sue Yoshitaka", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tachibana Muneshige", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tachibana Dōsetsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tachibana Ginchiyo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Taigen Sessai", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Taira no Kiyomori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Taira Masakado", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takahashi Shigetane", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takenaka Shigeharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takasugi Shinsaku", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takayama Justo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takayama Ukon", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takechi Hanpeita", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takeda Katsuyori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takeda Nobukatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takeda Nobushige", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takeda Shingen", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Takenaka Hanbei", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tani Tadasumi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tōdō Takatora", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Toki Yorinari", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tochimitsu Gantyoki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tokugawa Ieyasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tokugawa Hidetada", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tokugawa Nariaki", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tokugawa Yoshinobu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Torii Mototada", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Toyotomi Hidenaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Toyotomi Hideyoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Toyotomi Hideyori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tozuka Tadaharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Tsukahara Bokuden", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Uesugi Kagekatsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Uesugi Kagetora", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Uesugi Kenshin", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ujiie Naotomo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ukita Naoie", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Ukita Okiie", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Umezawa Michiharu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Usami Sadamitsu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Uyama Hisanobu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Wada Shinsuke", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Watanabe Kazan", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Watanabe no Tsuna", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yasumero Kenshin", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yagyū Jūbei Mitsuyoshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yagyū Munenori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamauchi Kazutoyo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamada Arinaga", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamada Arinobu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamada Nagamasa", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamagata Masakage", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamakawa Hiroshi", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamakawa Kenjirō", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamakawa Naoe", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamanaka Yukimori", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamanami Keisuke", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yamaoka Tesshū", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yanagawa Kenzaburo", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yanagisawa Yoshiyasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yonekura Shigetsugu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yūki Hideyasu", Strength = r.Next(2000) });
            modelBuilder.Entity<Samourai>().HasData(new Samourai { Id = idSamourai++, Name = "Yasuke", Strength = r.Next(2000) });
        }
    }
}
