using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Dojo.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class Initiale : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Arme",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Damage = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Arme", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "ArtMartial",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ArtMartial", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Samourai",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Strength = table.Column<int>(type: "int", nullable: false),
                    ArmeId = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Samourai", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Samourai_Arme_ArmeId",
                        column: x => x.ArmeId,
                        principalTable: "Arme",
                        principalColumn: "Id");
                });

            migrationBuilder.InsertData(
                table: "Arme",
                columns: new[] { "Id", "Damage", "Name" },
                values: new object[,]
                {
                    { 1, 426, "Katana" },
                    { 2, 230, "Yumi" },
                    { 3, 130, "Wakisashi" },
                    { 4, 403, "Naginata" },
                    { 5, 37, "Yari" },
                    { 6, 296, "Masakari" },
                    { 7, 339, "Nodachi" },
                    { 8, 487, "Tessen" },
                    { 9, 404, "Tachi" },
                    { 10, 128, "Shuriken" }
                });

            migrationBuilder.InsertData(
                table: "ArtMartial",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Krav Maga" },
                    { 2, "Keysi Fighting Method" },
                    { 3, "Jiu-Jitsu Brésilien" },
                    { 4, "Judo" },
                    { 5, "Muay Thai" },
                    { 6, "Taekwondo" },
                    { 7, "Jujutsu japonais" },
                    { 8, "Aïkido" },
                    { 9, "Boxe" },
                    { 10, "Karaté" }
                });

            migrationBuilder.InsertData(
                table: "Samourai",
                columns: new[] { "Id", "ArmeId", "Name", "Strength" },
                values: new object[,]
                {
                    { 1, null, "Abe Masakatsu", 1393 },
                    { 2, null, "Adachi Yasumori", 1296 },
                    { 3, null, "Adachi Kagemori", 159 },
                    { 4, null, "Adams William", 1169 },
                    { 5, null, "Aiou Mototsuna", 1941 },
                    { 6, null, "Akai Terukage", 1801 },
                    { 7, null, "Akao Kiyotsuna", 295 },
                    { 8, null, "Akechi Mitsuhide", 1791 },
                    { 9, null, "Akiyama Nobutomo", 1580 },
                    { 10, null, "Amago Haruhisa", 1217 },
                    { 11, null, "Amago Yoshihisa", 1316 },
                    { 12, null, "Andō Morinari", 1951 },
                    { 13, null, "Ankokuji Ekei", 1150 },
                    { 14, null, "Aochi Shigetsuna", 812 },
                    { 15, null, "Aokage Takaakira", 286 },
                    { 16, null, "Aoki Kazushige", 1319 },
                    { 17, null, "Akahori Chohichi", 192 },
                    { 18, null, "Arai Hakuseki", 229 },
                    { 19, null, "Araki Motokiyo", 892 },
                    { 20, null, "Araki Murashige", 1501 },
                    { 21, null, "Araki Muratsugu", 843 },
                    { 22, null, "Arima Kihei", 1751 },
                    { 23, null, "Asakura Yoshikage", 1509 },
                    { 24, null, "Ayame Kagekatsu", 1603 },
                    { 25, null, "Azai Hisamasa", 714 },
                    { 26, null, "Azai Nagamasa", 1385 },
                    { 27, null, "Azai Sukemasa", 188 },
                    { 28, null, "Baba Nobufusa", 1494 },
                    { 29, null, "Bessho Nagaharu", 204 },
                    { 30, null, "Chacha", 885 },
                    { 31, null, "Chiba Shusaku Narimasa", 448 },
                    { 32, null, "Chōsokabe Morichika", 1499 },
                    { 33, null, "Chōsokabe Kunichika", 1300 },
                    { 34, null, "Chōsokabe Motochika", 599 },
                    { 35, null, "Chōsokabe Nobuchika", 10 },
                    { 36, null, "Collache Eugène", 282 },
                    { 37, null, "Date Masamune", 737 },
                    { 38, null, "Date Shigezane", 1112 },
                    { 39, null, "Doi Toshikatsu", 1757 },
                    { 40, null, "Etō Shinpei", 616 },
                    { 41, null, "Endō Naotsune", 1980 },
                    { 42, null, "Enjoji Nobutane", 1672 },
                    { 43, null, "Enomoto Takeaki", 1875 },
                    { 44, null, "Era Fusahide", 961 },
                    { 45, null, "Fūma Kotarō", 1284 },
                    { 46, null, "Fuwa Mitsuharu", 209 },
                    { 47, null, "Fukushima Masanori", 1898 },
                    { 48, null, "Gamō Katahide", 843 },
                    { 49, null, "Gamō Ujisato", 1967 },
                    { 50, null, "Harada Naomasa", 1080 },
                    { 51, null, "Harada Nobutane", 949 },
                    { 52, null, "Harada Sanosuke", 753 },
                    { 53, null, "Hasekura Tsunenaga", 16 },
                    { 54, null, "Hattori Hanzō", 872 },
                    { 55, null, "Hatano Hideharu", 1931 },
                    { 56, null, "Hasegawa Eishin", 960 },
                    { 57, null, "Hayashizaki Jinsuke Shigenobu", 481 },
                    { 58, null, "Hayashi Narinaga", 981 },
                    { 59, null, "Hijikata Toshizo", 1264 },
                    { 60, null, "Hirate Masahide", 1467 },
                    { 61, null, "Hitotsubashi Keiki", 763 },
                    { 62, null, "Hōjō Masako", 780 },
                    { 63, null, "Hōjō Tokimune", 167 },
                    { 64, null, "Hōjō Ujiyasu", 1757 },
                    { 65, null, "Hōjō Ujimasa", 695 },
                    { 66, null, "Honda Tadakatsu", 1959 },
                    { 67, null, "Honda Tadatomo", 1817 },
                    { 68, null, "Honganji Kennyo", 1976 },
                    { 69, null, "Horio Yoshiharu", 1983 },
                    { 70, null, "Hosokawa Fujitaka", 1216 },
                    { 71, null, "Hosokawa Gracia", 578 },
                    { 72, null, "Hosokawa Tadaoki", 326 },
                    { 73, null, "Hotta Masatoshi", 1199 },
                    { 74, null, "Ii Naoaki", 230 },
                    { 75, null, "Ii Naomasa", 1316 },
                    { 76, null, "Ii Naomori", 994 },
                    { 77, null, "Ii Naonaka", 1717 },
                    { 78, null, "Ii Naosuke", 1133 },
                    { 79, null, "Ii Naotaka", 1892 },
                    { 80, null, "Ii Naotora", 1895 },
                    { 81, null, "Ii Naoyuki", 1721 },
                    { 82, null, "Ii Naozumi", 815 },
                    { 83, null, "Iizasa Ienao", 1841 },
                    { 84, null, "Ijuin Tadaaki", 516 },
                    { 85, null, "Ikeda Tsuneoki", 909 },
                    { 86, null, "Imagawa Ujizane", 1931 },
                    { 87, null, "Imagawa Yoshimoto", 436 },
                    { 88, null, "Imai Kanehira", 1279 },
                    { 89, null, "Inaba Yoshimichi", 1746 },
                    { 90, null, "Inugami Nagayasu", 1107 },
                    { 91, null, "Ishida Mitsunari", 368 },
                    { 92, null, "Isshiki Fujinaga", 1607 },
                    { 93, null, "Itagaki Nobukata", 239 },
                    { 94, null, "Itō Hirobumi", 102 },
                    { 95, null, "Iwanari Tomomichi", 1000 },
                    { 96, null, "Jinbo Nagamoto", 1604 },
                    { 97, null, "Jonas Tönse", 494 },
                    { 98, null, "Kannan Kumar(Salem)", 1426 },
                    { 99, null, "Kakeda Toshimune", 1409 },
                    { 100, null, "Kaneko Ietada", 864 },
                    { 101, null, "Katagiri Katsumoto", 891 },
                    { 102, null, "Katakura Kojūro", 964 },
                    { 103, null, "Katakura Shigenaga", 426 },
                    { 104, null, "Kataoka Mitsumasa", 1265 },
                    { 105, null, "Katō Kiyomasa", 298 },
                    { 106, null, "Kawakami Gensai", 250 },
                    { 107, null, "Kido Takayoshi", 1410 },
                    { 108, null, "Kikkawa Hiroie", 1094 },
                    { 109, null, "Kimotsuki Kanetsugu", 1508 },
                    { 110, null, "Kitamura Kansuke", 1149 },
                    { 111, null, "Kobayakawa Hideaki", 1589 },
                    { 112, null, "Kobayakawa Hidekane", 463 },
                    { 113, null, "Kobayakawa Takakage", 1675 },
                    { 114, null, "Konishi Yukinaga", 1559 },
                    { 115, null, "Kojima Toyoharu", 266 },
                    { 116, null, "Kuroda Kanbei", 352 },
                    { 117, null, "Kuroda Kiyotaka", 297 },
                    { 118, null, "Kusunoki Masashige", 30 },
                    { 119, null, "Kuwana Tarozaemon", 834 },
                    { 120, null, "Kumagai Naozane", 868 },
                    { 121, null, "Maeda Keiji", 1716 },
                    { 122, null, "Maeda Matsu", 430 },
                    { 123, null, "Maeda Nagatane", 434 },
                    { 124, null, "Maeda Toshiie", 1032 },
                    { 125, null, "Maeda Toshinaga", 603 },
                    { 126, null, "Maeda Toshitsune", 54 },
                    { 127, null, "Magome Kageyu", 691 },
                    { 128, null, "Manabe Akifusa", 691 },
                    { 129, null, "Matsudaira Katamori", 1185 },
                    { 130, null, "Matsudaira Nobutsuna", 1119 },
                    { 131, null, "Matsudaira Nobuyasu", 553 },
                    { 132, null, "Matsudaira Higo no Kami Katamori", 1032 },
                    { 133, null, "Matsudaira Sadanobu", 1371 },
                    { 134, null, "Matsudaira Tadayoshi", 101 },
                    { 135, null, "Matsudaira Teru", 1245 },
                    { 136, null, "Matsunaga Hisahide", 1400 },
                    { 137, null, "Matsunaga Hisamichi", 1338 },
                    { 138, null, "Matsuo Bashō", 1763 },
                    { 139, null, "Matsudaira Motoyasu", 1433 },
                    { 140, null, "Minamoto no Mitsunaka", 1102 },
                    { 141, null, "Minamoto no Yoshiie", 1872 },
                    { 142, null, "Minamoto no Yoshimitsu", 1203 },
                    { 143, null, "Minamoto no Yoshinaka", 817 },
                    { 144, null, "Minamoto no Yoshitomo", 1142 },
                    { 145, null, "Minamoto no Yoshitsune", 117 },
                    { 146, null, "Minamoto no Tameyoshi", 213 },
                    { 147, null, "Minamoto no Yorimasa", 1418 },
                    { 148, null, "Minamoto no Yorimitsu", 245 },
                    { 149, null, "Minamoto no Yoritomo", 1199 },
                    { 150, null, "Minamoto no Noriyori", 171 },
                    { 151, null, "Minoro Takashi", 1303 },
                    { 152, null, "Miura Anjin", 507 },
                    { 153, null, "Miura Yoshimoto", 1668 },
                    { 154, null, "Miyamoto Musashi", 676 },
                    { 155, null, "Miyoshi Chōkei", 12 },
                    { 156, null, "Miyoshi Kazuhide", 1437 },
                    { 157, null, "Miyoshi Masaga", 1928 },
                    { 158, null, "Miyoshi Masayasu", 1002 },
                    { 159, null, "Miyoshi Moriyata", 1237 },
                    { 160, null, "Miyoshi Nagayuki", 1081 },
                    { 161, null, "Miyoshi Yoshitsugu", 994 },
                    { 162, null, "Mizuno Tadakuni", 73 },
                    { 163, null, "Moniwa Yoshinao", 1315 },
                    { 164, null, "Mōri Motonari", 924 },
                    { 165, null, "Mōri Nagasada", 1885 },
                    { 166, null, "Mori Nagayoshi", 1386 },
                    { 167, null, "Mōri Okimoto", 1713 },
                    { 168, null, "Mori Ranmaru", 1138 },
                    { 169, null, "Mōri Takamoto", 1182 },
                    { 170, null, "Mori Tadamasa", 535 },
                    { 171, null, "Mōri Terumoto", 1476 },
                    { 172, null, "Mori Yoshinari", 1220 },
                    { 173, null, "Murai Sadakatsu", 1212 },
                    { 174, null, "Nagakura Shinpachi", 1191 },
                    { 175, null, "Nagao Harukage", 297 },
                    { 176, null, "Nagao Kagenobu", 20 },
                    { 177, null, "Nagao Masakage", 1853 },
                    { 178, null, "Nagao Tamekage", 576 },
                    { 179, null, "Nakagawa Kiyohide", 670 },
                    { 180, null, "Nakaoka Shintarō", 1622 },
                    { 181, null, "Naoe Kagetsuna", 1190 },
                    { 182, null, "Naoe Kanetsugu", 1236 },
                    { 183, null, "Narita Kaihime", 612 },
                    { 184, null, "Nene", 1189 },
                    { 185, null, "Nihonmatsu Yoshitsugu", 334 },
                    { 186, null, "Niimi Nishiki", 1651 },
                    { 187, null, "Niiro Tadamoto", 1518 },
                    { 188, null, "Niwa Nagahide", 210 },
                    { 189, null, "Niwa Nagashige", 1768 },
                    { 190, null, "Oda Hiroyoshi", 1947 },
                    { 191, null, "Oda Nobuhide", 1151 },
                    { 192, null, "Oda Nobukata", 1088 },
                    { 193, null, "Oda Nobukiyo", 483 },
                    { 194, null, "Oda Nobunaga", 1135 },
                    { 195, null, "Oda Nobutada", 1238 },
                    { 196, null, "Oda Nobutomo", 1486 },
                    { 197, null, "Oda Nobukatsu", 765 },
                    { 198, null, "Oda Nobuyasu", 188 },
                    { 199, null, "Ogasawara Shōsai", 1158 },
                    { 200, null, "Ōishi Kuranosuke", 63 },
                    { 201, null, "Okada Izō", 14 },
                    { 202, null, "Judge Ooka", 1486 },
                    { 203, null, "Ōta Dōkan", 297 },
                    { 204, null, "Ōtani Yoshitsugu", 1801 },
                    { 205, null, "Ōtani Yoshiharu", 1143 },
                    { 206, null, "Ōtomo Sōrin", 1640 },
                    { 207, null, "Okita Sōji", 124 },
                    { 208, null, "Ōkubo Toshimichi", 360 },
                    { 209, null, "Okunomiya Masaie", 1430 },
                    { 210, null, "Ōuchi Yoshitaka", 952 },
                    { 211, null, "Omy Yoshika", 1513 },
                    { 212, null, "Pore Sufi", 620 },
                    { 213, null, "Reizei Takatoyo", 1158 },
                    { 214, null, "Rokkaku Sadayori", 1079 },
                    { 215, null, "Rokkaku Yoshiharu", 47 },
                    { 216, null, "Rokkaku Yoshikata", 898 },
                    { 217, null, "Rusu Masakage", 671 },
                    { 218, null, "Ryūzōji Takanobu", 205 },
                    { 219, null, "Saigo Kiyokazu", 1652 },
                    { 220, null, "Saigō Masako", 455 },
                    { 221, null, "Sagara Taketō", 483 },
                    { 222, null, "Saigō Takamori", 1530 },
                    { 223, null, "Saigo Yoshikatsu", 1071 },
                    { 224, null, "Saitō Dōsan", 1465 },
                    { 225, null, "Saitō Hajime", 493 },
                    { 226, null, "Saito Musashibō Benkei", 129 },
                    { 227, null, "Saitō Yoshitatsu", 1198 },
                    { 228, null, "Sakai Tadakiyo", 921 },
                    { 229, null, "Sakai Tadashige", 86 },
                    { 230, null, "Sakai Tadatsugu", 1566 },
                    { 231, null, "Sakai Tadayo", 1053 },
                    { 232, null, "Sakakibara Yasumasa", 1429 },
                    { 233, null, "Sakamoto Ryōma", 47 },
                    { 234, null, "Sakuma Morimasa", 1180 },
                    { 235, null, "Sakuma Nobumori", 1087 },
                    { 236, null, "Sanada Akihime", 1769 },
                    { 237, null, "Sanada Komatsuhime", 1206 },
                    { 238, null, "Sanada Masayuki", 1053 },
                    { 239, null, "Sanada Nobuyuki", 1111 },
                    { 240, null, "Sanada Yukimura", 1509 },
                    { 241, null, "Sasaki Kojirō", 422 },
                    { 242, null, "Sassa Narimasa", 1538 },
                    { 243, null, "Sasuke Sarutobi", 1181 },
                    { 244, null, "Serizawa Kamo", 1414 },
                    { 245, null, "Shibata Katsuie", 1757 },
                    { 246, null, "Shima Sakon", 323 },
                    { 247, null, "Shimada Ichirō", 1923 },
                    { 248, null, "Shimazu Katsuhisa", 479 },
                    { 249, null, "Shimazu Tadahisa", 1897 },
                    { 250, null, "Shimazu Tadatsune", 1056 },
                    { 251, null, "Shimazu Tadayoshi", 728 },
                    { 252, null, "Shimazu Takahisa", 414 },
                    { 253, null, "Shimazu Toyohisa", 1239 },
                    { 254, null, "Shimazu Yoshihiro", 236 },
                    { 255, null, "Shimazu Yoshihisa", 440 },
                    { 256, null, "Shindou Hiroshii", 1549 },
                    { 257, null, "Sogo Nagayasu", 1328 },
                    { 258, null, "Sue Yoshitaka", 1883 },
                    { 259, null, "Tachibana Muneshige", 1104 },
                    { 260, null, "Tachibana Dōsetsu", 668 },
                    { 261, null, "Tachibana Ginchiyo", 483 },
                    { 262, null, "Taigen Sessai", 618 },
                    { 263, null, "Taira no Kiyomori", 1131 },
                    { 264, null, "Taira Masakado", 1634 },
                    { 265, null, "Takahashi Shigetane", 227 },
                    { 266, null, "Takenaka Shigeharu", 976 },
                    { 267, null, "Takasugi Shinsaku", 327 },
                    { 268, null, "Takayama Justo", 1689 },
                    { 269, null, "Takayama Ukon", 240 },
                    { 270, null, "Takechi Hanpeita", 1404 },
                    { 271, null, "Takeda Katsuyori", 1485 },
                    { 272, null, "Takeda Nobukatsu", 1018 },
                    { 273, null, "Takeda Nobushige", 576 },
                    { 274, null, "Takeda Shingen", 72 },
                    { 275, null, "Takenaka Hanbei", 1143 },
                    { 276, null, "Tani Tadasumi", 622 },
                    { 277, null, "Tōdō Takatora", 1195 },
                    { 278, null, "Toki Yorinari", 1883 },
                    { 279, null, "Tochimitsu Gantyoki", 972 },
                    { 280, null, "Tokugawa Ieyasu", 1379 },
                    { 281, null, "Tokugawa Hidetada", 903 },
                    { 282, null, "Tokugawa Nariaki", 315 },
                    { 283, null, "Tokugawa Yoshinobu", 360 },
                    { 284, null, "Torii Mototada", 1023 },
                    { 285, null, "Toyotomi Hidenaga", 715 },
                    { 286, null, "Toyotomi Hideyoshi", 915 },
                    { 287, null, "Toyotomi Hideyori", 861 },
                    { 288, null, "Tozuka Tadaharu", 858 },
                    { 289, null, "Tsukahara Bokuden", 1646 },
                    { 290, null, "Uesugi Kagekatsu", 1900 },
                    { 291, null, "Uesugi Kagetora", 1812 },
                    { 292, null, "Uesugi Kenshin", 1401 },
                    { 293, null, "Ujiie Naotomo", 965 },
                    { 294, null, "Ukita Naoie", 1067 },
                    { 295, null, "Ukita Okiie", 1082 },
                    { 296, null, "Umezawa Michiharu", 1308 },
                    { 297, null, "Usami Sadamitsu", 1554 },
                    { 298, null, "Uyama Hisanobu", 466 },
                    { 299, null, "Wada Shinsuke", 405 },
                    { 300, null, "Watanabe Kazan", 781 },
                    { 301, null, "Watanabe no Tsuna", 923 },
                    { 302, null, "Yasumero Kenshin", 1939 },
                    { 303, null, "Yagyū Jūbei Mitsuyoshi", 106 },
                    { 304, null, "Yagyū Munenori", 714 },
                    { 305, null, "Yamauchi Kazutoyo", 654 },
                    { 306, null, "Yamada Arinaga", 471 },
                    { 307, null, "Yamada Arinobu", 1192 },
                    { 308, null, "Yamada Nagamasa", 366 },
                    { 309, null, "Yamagata Masakage", 387 },
                    { 310, null, "Yamakawa Hiroshi", 1720 },
                    { 311, null, "Yamakawa Kenjirō", 1568 },
                    { 312, null, "Yamakawa Naoe", 1665 },
                    { 313, null, "Yamanaka Yukimori", 1182 },
                    { 314, null, "Yamanami Keisuke", 1687 },
                    { 315, null, "Yamaoka Tesshū", 1909 },
                    { 316, null, "Yanagawa Kenzaburo", 1796 },
                    { 317, null, "Yanagisawa Yoshiyasu", 57 },
                    { 318, null, "Yonekura Shigetsugu", 688 },
                    { 319, null, "Yūki Hideyasu", 958 },
                    { 320, null, "Yasuke", 736 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Samourai_ArmeId",
                table: "Samourai",
                column: "ArmeId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ArtMartial");

            migrationBuilder.DropTable(
                name: "Samourai");

            migrationBuilder.DropTable(
                name: "Arme");
        }
    }
}
