using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Dojo.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class Initiale : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Arme",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Damage = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Arme", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Samourai",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Strength = table.Column<int>(type: "int", nullable: false),
                    ArmeId = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Samourai", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Samourai_Arme_ArmeId",
                        column: x => x.ArmeId,
                        principalTable: "Arme",
                        principalColumn: "Id");
                });

            migrationBuilder.InsertData(
                table: "Samourai",
                columns: new[] { "Id", "ArmeId", "Name", "Strength" },
                values: new object[,]
                {
                    { 1, null, "Abe Masakatsu", 43 },
                    { 2, null, "Adachi Yasumori", 71 },
                    { 3, null, "Adachi Kagemori", 1944 },
                    { 4, null, "Adams William", 293 },
                    { 5, null, "Aiou Mototsuna", 471 },
                    { 6, null, "Akai Terukage", 1469 },
                    { 7, null, "Akao Kiyotsuna", 495 },
                    { 8, null, "Akechi Mitsuhide", 1966 },
                    { 9, null, "Akiyama Nobutomo", 1740 },
                    { 10, null, "Amago Haruhisa", 1320 },
                    { 11, null, "Amago Yoshihisa", 126 },
                    { 12, null, "Andō Morinari", 546 },
                    { 13, null, "Ankokuji Ekei", 1541 },
                    { 14, null, "Aochi Shigetsuna", 596 },
                    { 15, null, "Aokage Takaakira", 1987 },
                    { 16, null, "Aoki Kazushige", 210 },
                    { 17, null, "Akahori Chohichi", 1654 },
                    { 18, null, "Arai Hakuseki", 1213 },
                    { 19, null, "Araki Motokiyo", 1842 },
                    { 20, null, "Araki Murashige", 22 },
                    { 21, null, "Araki Muratsugu", 25 },
                    { 22, null, "Arima Kihei", 160 },
                    { 23, null, "Asakura Yoshikage", 1931 },
                    { 24, null, "Ayame Kagekatsu", 1598 },
                    { 25, null, "Azai Hisamasa", 1995 },
                    { 26, null, "Azai Nagamasa", 889 },
                    { 27, null, "Azai Sukemasa", 1847 },
                    { 28, null, "Baba Nobufusa", 692 },
                    { 29, null, "Bessho Nagaharu", 1541 },
                    { 30, null, "Chacha", 286 },
                    { 31, null, "Chiba Shusaku Narimasa", 1578 },
                    { 32, null, "Chōsokabe Morichika", 127 },
                    { 33, null, "Chōsokabe Kunichika", 1110 },
                    { 34, null, "Chōsokabe Motochika", 322 },
                    { 35, null, "Chōsokabe Nobuchika", 1709 },
                    { 36, null, "Collache Eugène", 890 },
                    { 37, null, "Date Masamune", 889 },
                    { 38, null, "Date Shigezane", 512 },
                    { 39, null, "Doi Toshikatsu", 1067 },
                    { 40, null, "Etō Shinpei", 13 },
                    { 41, null, "Endō Naotsune", 237 },
                    { 42, null, "Enjoji Nobutane", 797 },
                    { 43, null, "Enomoto Takeaki", 280 },
                    { 44, null, "Era Fusahide", 409 },
                    { 45, null, "Fūma Kotarō", 114 },
                    { 46, null, "Fuwa Mitsuharu", 404 },
                    { 47, null, "Fukushima Masanori", 675 },
                    { 48, null, "Gamō Katahide", 536 },
                    { 49, null, "Gamō Ujisato", 748 },
                    { 50, null, "Harada Naomasa", 1178 },
                    { 51, null, "Harada Nobutane", 890 },
                    { 52, null, "Harada Sanosuke", 854 },
                    { 53, null, "Hasekura Tsunenaga", 174 },
                    { 54, null, "Hattori Hanzō", 561 },
                    { 55, null, "Hatano Hideharu", 1434 },
                    { 56, null, "Hasegawa Eishin", 927 },
                    { 57, null, "Hayashizaki Jinsuke Shigenobu", 1676 },
                    { 58, null, "Hayashi Narinaga", 720 },
                    { 59, null, "Hijikata Toshizo", 263 },
                    { 60, null, "Hirate Masahide", 1528 },
                    { 61, null, "Hitotsubashi Keiki", 34 },
                    { 62, null, "Hōjō Masako", 888 },
                    { 63, null, "Hōjō Tokimune", 1065 },
                    { 64, null, "Hōjō Ujiyasu", 593 },
                    { 65, null, "Hōjō Ujimasa", 991 },
                    { 66, null, "Honda Tadakatsu", 1321 },
                    { 67, null, "Honda Tadatomo", 922 },
                    { 68, null, "Honganji Kennyo", 474 },
                    { 69, null, "Horio Yoshiharu", 1900 },
                    { 70, null, "Hosokawa Fujitaka", 1927 },
                    { 71, null, "Hosokawa Gracia", 693 },
                    { 72, null, "Hosokawa Tadaoki", 208 },
                    { 73, null, "Hotta Masatoshi", 1301 },
                    { 74, null, "Ii Naoaki", 142 },
                    { 75, null, "Ii Naomasa", 615 },
                    { 76, null, "Ii Naomori", 1867 },
                    { 77, null, "Ii Naonaka", 1857 },
                    { 78, null, "Ii Naosuke", 718 },
                    { 79, null, "Ii Naotaka", 184 },
                    { 80, null, "Ii Naotora", 1971 },
                    { 81, null, "Ii Naoyuki", 428 },
                    { 82, null, "Ii Naozumi", 1089 },
                    { 83, null, "Iizasa Ienao", 1146 },
                    { 84, null, "Ijuin Tadaaki", 406 },
                    { 85, null, "Ikeda Tsuneoki", 846 },
                    { 86, null, "Imagawa Ujizane", 786 },
                    { 87, null, "Imagawa Yoshimoto", 908 },
                    { 88, null, "Imai Kanehira", 188 },
                    { 89, null, "Inaba Yoshimichi", 1787 },
                    { 90, null, "Inugami Nagayasu", 1587 },
                    { 91, null, "Ishida Mitsunari", 1586 },
                    { 92, null, "Isshiki Fujinaga", 655 },
                    { 93, null, "Itagaki Nobukata", 952 },
                    { 94, null, "Itō Hirobumi", 1301 },
                    { 95, null, "Iwanari Tomomichi", 1540 },
                    { 96, null, "Jinbo Nagamoto", 334 },
                    { 97, null, "Jonas Tönse", 304 },
                    { 98, null, "Kannan Kumar(Salem)", 1820 },
                    { 99, null, "Kakeda Toshimune", 1596 },
                    { 100, null, "Kaneko Ietada", 165 },
                    { 101, null, "Katagiri Katsumoto", 1768 },
                    { 102, null, "Katakura Kojūro", 1791 },
                    { 103, null, "Katakura Shigenaga", 245 },
                    { 104, null, "Kataoka Mitsumasa", 887 },
                    { 105, null, "Katō Kiyomasa", 1568 },
                    { 106, null, "Kawakami Gensai", 669 },
                    { 107, null, "Kido Takayoshi", 126 },
                    { 108, null, "Kikkawa Hiroie", 512 },
                    { 109, null, "Kimotsuki Kanetsugu", 1591 },
                    { 110, null, "Kitamura Kansuke", 1376 },
                    { 111, null, "Kobayakawa Hideaki", 1545 },
                    { 112, null, "Kobayakawa Hidekane", 1565 },
                    { 113, null, "Kobayakawa Takakage", 1120 },
                    { 114, null, "Konishi Yukinaga", 1677 },
                    { 115, null, "Kojima Toyoharu", 1432 },
                    { 116, null, "Kuroda Kanbei", 1614 },
                    { 117, null, "Kuroda Kiyotaka", 1928 },
                    { 118, null, "Kusunoki Masashige", 194 },
                    { 119, null, "Kuwana Tarozaemon", 430 },
                    { 120, null, "Kumagai Naozane", 139 },
                    { 121, null, "Maeda Keiji", 935 },
                    { 122, null, "Maeda Matsu", 1652 },
                    { 123, null, "Maeda Nagatane", 825 },
                    { 124, null, "Maeda Toshiie", 230 },
                    { 125, null, "Maeda Toshinaga", 441 },
                    { 126, null, "Maeda Toshitsune", 1837 },
                    { 127, null, "Magome Kageyu", 963 },
                    { 128, null, "Manabe Akifusa", 757 },
                    { 129, null, "Matsudaira Katamori", 407 },
                    { 130, null, "Matsudaira Nobutsuna", 791 },
                    { 131, null, "Matsudaira Nobuyasu", 1721 },
                    { 132, null, "Matsudaira Higo no Kami Katamori", 1343 },
                    { 133, null, "Matsudaira Sadanobu", 1257 },
                    { 134, null, "Matsudaira Tadayoshi", 18 },
                    { 135, null, "Matsudaira Teru", 135 },
                    { 136, null, "Matsunaga Hisahide", 1292 },
                    { 137, null, "Matsunaga Hisamichi", 1226 },
                    { 138, null, "Matsuo Bashō", 1202 },
                    { 139, null, "Matsudaira Motoyasu", 1074 },
                    { 140, null, "Minamoto no Mitsunaka", 1292 },
                    { 141, null, "Minamoto no Yoshiie", 465 },
                    { 142, null, "Minamoto no Yoshimitsu", 52 },
                    { 143, null, "Minamoto no Yoshinaka", 504 },
                    { 144, null, "Minamoto no Yoshitomo", 923 },
                    { 145, null, "Minamoto no Yoshitsune", 380 },
                    { 146, null, "Minamoto no Tameyoshi", 1188 },
                    { 147, null, "Minamoto no Yorimasa", 215 },
                    { 148, null, "Minamoto no Yorimitsu", 795 },
                    { 149, null, "Minamoto no Yoritomo", 338 },
                    { 150, null, "Minamoto no Noriyori", 1767 },
                    { 151, null, "Minoro Takashi", 470 },
                    { 152, null, "Miura Anjin", 342 },
                    { 153, null, "Miura Yoshimoto", 1558 },
                    { 154, null, "Miyamoto Musashi", 556 },
                    { 155, null, "Miyoshi Chōkei", 303 },
                    { 156, null, "Miyoshi Kazuhide", 1863 },
                    { 157, null, "Miyoshi Masaga", 1772 },
                    { 158, null, "Miyoshi Masayasu", 1250 },
                    { 159, null, "Miyoshi Moriyata", 1670 },
                    { 160, null, "Miyoshi Nagayuki", 1534 },
                    { 161, null, "Miyoshi Yoshitsugu", 1614 },
                    { 162, null, "Mizuno Tadakuni", 1635 },
                    { 163, null, "Moniwa Yoshinao", 773 },
                    { 164, null, "Mōri Motonari", 454 },
                    { 165, null, "Mōri Nagasada", 952 },
                    { 166, null, "Mori Nagayoshi", 702 },
                    { 167, null, "Mōri Okimoto", 1702 },
                    { 168, null, "Mori Ranmaru", 281 },
                    { 169, null, "Mōri Takamoto", 1311 },
                    { 170, null, "Mori Tadamasa", 1222 },
                    { 171, null, "Mōri Terumoto", 1209 },
                    { 172, null, "Mori Yoshinari", 1385 },
                    { 173, null, "Murai Sadakatsu", 833 },
                    { 174, null, "Nagakura Shinpachi", 1436 },
                    { 175, null, "Nagao Harukage", 1466 },
                    { 176, null, "Nagao Kagenobu", 1960 },
                    { 177, null, "Nagao Masakage", 324 },
                    { 178, null, "Nagao Tamekage", 829 },
                    { 179, null, "Nakagawa Kiyohide", 409 },
                    { 180, null, "Nakaoka Shintarō", 1592 },
                    { 181, null, "Naoe Kagetsuna", 1027 },
                    { 182, null, "Naoe Kanetsugu", 496 },
                    { 183, null, "Narita Kaihime", 531 },
                    { 184, null, "Nene", 1271 },
                    { 185, null, "Nihonmatsu Yoshitsugu", 1018 },
                    { 186, null, "Niimi Nishiki", 473 },
                    { 187, null, "Niiro Tadamoto", 79 },
                    { 188, null, "Niwa Nagahide", 841 },
                    { 189, null, "Niwa Nagashige", 930 },
                    { 190, null, "Oda Hiroyoshi", 1495 },
                    { 191, null, "Oda Nobuhide", 1265 },
                    { 192, null, "Oda Nobukata", 24 },
                    { 193, null, "Oda Nobukiyo", 1502 },
                    { 194, null, "Oda Nobunaga", 1190 },
                    { 195, null, "Oda Nobutada", 988 },
                    { 196, null, "Oda Nobutomo", 197 },
                    { 197, null, "Oda Nobukatsu", 564 },
                    { 198, null, "Oda Nobuyasu", 1824 },
                    { 199, null, "Ogasawara Shōsai", 511 },
                    { 200, null, "Ōishi Kuranosuke", 764 },
                    { 201, null, "Okada Izō", 41 },
                    { 202, null, "Judge Ooka", 196 },
                    { 203, null, "Ōta Dōkan", 502 },
                    { 204, null, "Ōtani Yoshitsugu", 349 },
                    { 205, null, "Ōtani Yoshiharu", 987 },
                    { 206, null, "Ōtomo Sōrin", 292 },
                    { 207, null, "Okita Sōji", 663 },
                    { 208, null, "Ōkubo Toshimichi", 1065 },
                    { 209, null, "Okunomiya Masaie", 1136 },
                    { 210, null, "Ōuchi Yoshitaka", 1912 },
                    { 211, null, "Omy Yoshika", 1969 },
                    { 212, null, "Pore Sufi", 795 },
                    { 213, null, "Reizei Takatoyo", 1311 },
                    { 214, null, "Rokkaku Sadayori", 432 },
                    { 215, null, "Rokkaku Yoshiharu", 1114 },
                    { 216, null, "Rokkaku Yoshikata", 1059 },
                    { 217, null, "Rusu Masakage", 415 },
                    { 218, null, "Ryūzōji Takanobu", 1971 },
                    { 219, null, "Saigo Kiyokazu", 159 },
                    { 220, null, "Saigō Masako", 1172 },
                    { 221, null, "Sagara Taketō", 903 },
                    { 222, null, "Saigō Takamori", 874 },
                    { 223, null, "Saigo Yoshikatsu", 397 },
                    { 224, null, "Saitō Dōsan", 1591 },
                    { 225, null, "Saitō Hajime", 1095 },
                    { 226, null, "Saito Musashibō Benkei", 755 },
                    { 227, null, "Saitō Yoshitatsu", 962 },
                    { 228, null, "Sakai Tadakiyo", 1354 },
                    { 229, null, "Sakai Tadashige", 574 },
                    { 230, null, "Sakai Tadatsugu", 1981 },
                    { 231, null, "Sakai Tadayo", 882 },
                    { 232, null, "Sakakibara Yasumasa", 569 },
                    { 233, null, "Sakamoto Ryōma", 648 },
                    { 234, null, "Sakuma Morimasa", 486 },
                    { 235, null, "Sakuma Nobumori", 1393 },
                    { 236, null, "Sanada Akihime", 1877 },
                    { 237, null, "Sanada Komatsuhime", 1370 },
                    { 238, null, "Sanada Masayuki", 1976 },
                    { 239, null, "Sanada Nobuyuki", 47 },
                    { 240, null, "Sanada Yukimura", 1450 },
                    { 241, null, "Sasaki Kojirō", 1396 },
                    { 242, null, "Sassa Narimasa", 533 },
                    { 243, null, "Sasuke Sarutobi", 1117 },
                    { 244, null, "Serizawa Kamo", 1679 },
                    { 245, null, "Shibata Katsuie", 528 },
                    { 246, null, "Shima Sakon", 479 },
                    { 247, null, "Shimada Ichirō", 1203 },
                    { 248, null, "Shimazu Katsuhisa", 289 },
                    { 249, null, "Shimazu Tadahisa", 1454 },
                    { 250, null, "Shimazu Tadatsune", 803 },
                    { 251, null, "Shimazu Tadayoshi", 822 },
                    { 252, null, "Shimazu Takahisa", 853 },
                    { 253, null, "Shimazu Toyohisa", 555 },
                    { 254, null, "Shimazu Yoshihiro", 1457 },
                    { 255, null, "Shimazu Yoshihisa", 1992 },
                    { 256, null, "Shindou Hiroshii", 1680 },
                    { 257, null, "Sogo Nagayasu", 1117 },
                    { 258, null, "Sue Yoshitaka", 1485 },
                    { 259, null, "Tachibana Muneshige", 889 },
                    { 260, null, "Tachibana Dōsetsu", 1914 },
                    { 261, null, "Tachibana Ginchiyo", 9 },
                    { 262, null, "Taigen Sessai", 503 },
                    { 263, null, "Taira no Kiyomori", 238 },
                    { 264, null, "Taira Masakado", 111 },
                    { 265, null, "Takahashi Shigetane", 1415 },
                    { 266, null, "Takenaka Shigeharu", 944 },
                    { 267, null, "Takasugi Shinsaku", 226 },
                    { 268, null, "Takayama Justo", 547 },
                    { 269, null, "Takayama Ukon", 692 },
                    { 270, null, "Takechi Hanpeita", 1783 },
                    { 271, null, "Takeda Katsuyori", 1879 },
                    { 272, null, "Takeda Nobukatsu", 886 },
                    { 273, null, "Takeda Nobushige", 266 },
                    { 274, null, "Takeda Shingen", 190 },
                    { 275, null, "Takenaka Hanbei", 1046 },
                    { 276, null, "Tani Tadasumi", 297 },
                    { 277, null, "Tōdō Takatora", 804 },
                    { 278, null, "Toki Yorinari", 391 },
                    { 279, null, "Tochimitsu Gantyoki", 71 },
                    { 280, null, "Tokugawa Ieyasu", 1364 },
                    { 281, null, "Tokugawa Hidetada", 531 },
                    { 282, null, "Tokugawa Nariaki", 983 },
                    { 283, null, "Tokugawa Yoshinobu", 116 },
                    { 284, null, "Torii Mototada", 1020 },
                    { 285, null, "Toyotomi Hidenaga", 1114 },
                    { 286, null, "Toyotomi Hideyoshi", 422 },
                    { 287, null, "Toyotomi Hideyori", 1312 },
                    { 288, null, "Tozuka Tadaharu", 464 },
                    { 289, null, "Tsukahara Bokuden", 1231 },
                    { 290, null, "Uesugi Kagekatsu", 978 },
                    { 291, null, "Uesugi Kagetora", 1259 },
                    { 292, null, "Uesugi Kenshin", 1055 },
                    { 293, null, "Ujiie Naotomo", 1499 },
                    { 294, null, "Ukita Naoie", 1138 },
                    { 295, null, "Ukita Okiie", 1526 },
                    { 296, null, "Umezawa Michiharu", 1234 },
                    { 297, null, "Usami Sadamitsu", 1247 },
                    { 298, null, "Uyama Hisanobu", 1224 },
                    { 299, null, "Wada Shinsuke", 1422 },
                    { 300, null, "Watanabe Kazan", 873 },
                    { 301, null, "Watanabe no Tsuna", 1727 },
                    { 302, null, "Yasumero Kenshin", 1127 },
                    { 303, null, "Yagyū Jūbei Mitsuyoshi", 782 },
                    { 304, null, "Yagyū Munenori", 515 },
                    { 305, null, "Yamauchi Kazutoyo", 711 },
                    { 306, null, "Yamada Arinaga", 1799 },
                    { 307, null, "Yamada Arinobu", 1005 },
                    { 308, null, "Yamada Nagamasa", 1785 },
                    { 309, null, "Yamagata Masakage", 722 },
                    { 310, null, "Yamakawa Hiroshi", 1839 },
                    { 311, null, "Yamakawa Kenjirō", 423 },
                    { 312, null, "Yamakawa Naoe", 1819 },
                    { 313, null, "Yamanaka Yukimori", 1099 },
                    { 314, null, "Yamanami Keisuke", 1172 },
                    { 315, null, "Yamaoka Tesshū", 11 },
                    { 316, null, "Yanagawa Kenzaburo", 539 },
                    { 317, null, "Yanagisawa Yoshiyasu", 1465 },
                    { 318, null, "Yonekura Shigetsugu", 1572 },
                    { 319, null, "Yūki Hideyasu", 1529 },
                    { 320, null, "Yasuke", 187 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Samourai_ArmeId",
                table: "Samourai",
                column: "ArmeId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Samourai");

            migrationBuilder.DropTable(
                name: "Arme");
        }
    }
}
