// <auto-generated />
using System;
using Dojo.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dojo.Infrastructure.Migrations
{
    [DbContext(typeof(DojoContext))]
    partial class DojoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dojo.Domain.Entities.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Arme");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 426,
                            Name = "Katana"
                        },
                        new
                        {
                            Id = 2,
                            Damage = 230,
                            Name = "Yumi"
                        },
                        new
                        {
                            Id = 3,
                            Damage = 130,
                            Name = "Wakisashi"
                        },
                        new
                        {
                            Id = 4,
                            Damage = 403,
                            Name = "Naginata"
                        },
                        new
                        {
                            Id = 5,
                            Damage = 37,
                            Name = "Yari"
                        },
                        new
                        {
                            Id = 6,
                            Damage = 296,
                            Name = "Masakari"
                        },
                        new
                        {
                            Id = 7,
                            Damage = 339,
                            Name = "Nodachi"
                        },
                        new
                        {
                            Id = 8,
                            Damage = 487,
                            Name = "Tessen"
                        },
                        new
                        {
                            Id = 9,
                            Damage = 404,
                            Name = "Tachi"
                        },
                        new
                        {
                            Id = 10,
                            Damage = 128,
                            Name = "Shuriken"
                        });
                });

            modelBuilder.Entity("Dojo.Domain.Entities.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ArtMartial");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Krav Maga"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Keysi Fighting Method"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jiu-Jitsu Brésilien"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Judo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Muay Thai"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Taekwondo"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jujutsu japonais"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Aïkido"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Boxe"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Karaté"
                        });
                });

            modelBuilder.Entity("Dojo.Domain.Entities.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmeId");

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abe Masakatsu",
                            Strength = 1393
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adachi Yasumori",
                            Strength = 1296
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adachi Kagemori",
                            Strength = 159
                        },
                        new
                        {
                            Id = 4,
                            Name = "Adams William",
                            Strength = 1169
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aiou Mototsuna",
                            Strength = 1941
                        },
                        new
                        {
                            Id = 6,
                            Name = "Akai Terukage",
                            Strength = 1801
                        },
                        new
                        {
                            Id = 7,
                            Name = "Akao Kiyotsuna",
                            Strength = 295
                        },
                        new
                        {
                            Id = 8,
                            Name = "Akechi Mitsuhide",
                            Strength = 1791
                        },
                        new
                        {
                            Id = 9,
                            Name = "Akiyama Nobutomo",
                            Strength = 1580
                        },
                        new
                        {
                            Id = 10,
                            Name = "Amago Haruhisa",
                            Strength = 1217
                        },
                        new
                        {
                            Id = 11,
                            Name = "Amago Yoshihisa",
                            Strength = 1316
                        },
                        new
                        {
                            Id = 12,
                            Name = "Andō Morinari",
                            Strength = 1951
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ankokuji Ekei",
                            Strength = 1150
                        },
                        new
                        {
                            Id = 14,
                            Name = "Aochi Shigetsuna",
                            Strength = 812
                        },
                        new
                        {
                            Id = 15,
                            Name = "Aokage Takaakira",
                            Strength = 286
                        },
                        new
                        {
                            Id = 16,
                            Name = "Aoki Kazushige",
                            Strength = 1319
                        },
                        new
                        {
                            Id = 17,
                            Name = "Akahori Chohichi",
                            Strength = 192
                        },
                        new
                        {
                            Id = 18,
                            Name = "Arai Hakuseki",
                            Strength = 229
                        },
                        new
                        {
                            Id = 19,
                            Name = "Araki Motokiyo",
                            Strength = 892
                        },
                        new
                        {
                            Id = 20,
                            Name = "Araki Murashige",
                            Strength = 1501
                        },
                        new
                        {
                            Id = 21,
                            Name = "Araki Muratsugu",
                            Strength = 843
                        },
                        new
                        {
                            Id = 22,
                            Name = "Arima Kihei",
                            Strength = 1751
                        },
                        new
                        {
                            Id = 23,
                            Name = "Asakura Yoshikage",
                            Strength = 1509
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ayame Kagekatsu",
                            Strength = 1603
                        },
                        new
                        {
                            Id = 25,
                            Name = "Azai Hisamasa",
                            Strength = 714
                        },
                        new
                        {
                            Id = 26,
                            Name = "Azai Nagamasa",
                            Strength = 1385
                        },
                        new
                        {
                            Id = 27,
                            Name = "Azai Sukemasa",
                            Strength = 188
                        },
                        new
                        {
                            Id = 28,
                            Name = "Baba Nobufusa",
                            Strength = 1494
                        },
                        new
                        {
                            Id = 29,
                            Name = "Bessho Nagaharu",
                            Strength = 204
                        },
                        new
                        {
                            Id = 30,
                            Name = "Chacha",
                            Strength = 885
                        },
                        new
                        {
                            Id = 31,
                            Name = "Chiba Shusaku Narimasa",
                            Strength = 448
                        },
                        new
                        {
                            Id = 32,
                            Name = "Chōsokabe Morichika",
                            Strength = 1499
                        },
                        new
                        {
                            Id = 33,
                            Name = "Chōsokabe Kunichika",
                            Strength = 1300
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chōsokabe Motochika",
                            Strength = 599
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chōsokabe Nobuchika",
                            Strength = 10
                        },
                        new
                        {
                            Id = 36,
                            Name = "Collache Eugène",
                            Strength = 282
                        },
                        new
                        {
                            Id = 37,
                            Name = "Date Masamune",
                            Strength = 737
                        },
                        new
                        {
                            Id = 38,
                            Name = "Date Shigezane",
                            Strength = 1112
                        },
                        new
                        {
                            Id = 39,
                            Name = "Doi Toshikatsu",
                            Strength = 1757
                        },
                        new
                        {
                            Id = 40,
                            Name = "Etō Shinpei",
                            Strength = 616
                        },
                        new
                        {
                            Id = 41,
                            Name = "Endō Naotsune",
                            Strength = 1980
                        },
                        new
                        {
                            Id = 42,
                            Name = "Enjoji Nobutane",
                            Strength = 1672
                        },
                        new
                        {
                            Id = 43,
                            Name = "Enomoto Takeaki",
                            Strength = 1875
                        },
                        new
                        {
                            Id = 44,
                            Name = "Era Fusahide",
                            Strength = 961
                        },
                        new
                        {
                            Id = 45,
                            Name = "Fūma Kotarō",
                            Strength = 1284
                        },
                        new
                        {
                            Id = 46,
                            Name = "Fuwa Mitsuharu",
                            Strength = 209
                        },
                        new
                        {
                            Id = 47,
                            Name = "Fukushima Masanori",
                            Strength = 1898
                        },
                        new
                        {
                            Id = 48,
                            Name = "Gamō Katahide",
                            Strength = 843
                        },
                        new
                        {
                            Id = 49,
                            Name = "Gamō Ujisato",
                            Strength = 1967
                        },
                        new
                        {
                            Id = 50,
                            Name = "Harada Naomasa",
                            Strength = 1080
                        },
                        new
                        {
                            Id = 51,
                            Name = "Harada Nobutane",
                            Strength = 949
                        },
                        new
                        {
                            Id = 52,
                            Name = "Harada Sanosuke",
                            Strength = 753
                        },
                        new
                        {
                            Id = 53,
                            Name = "Hasekura Tsunenaga",
                            Strength = 16
                        },
                        new
                        {
                            Id = 54,
                            Name = "Hattori Hanzō",
                            Strength = 872
                        },
                        new
                        {
                            Id = 55,
                            Name = "Hatano Hideharu",
                            Strength = 1931
                        },
                        new
                        {
                            Id = 56,
                            Name = "Hasegawa Eishin",
                            Strength = 960
                        },
                        new
                        {
                            Id = 57,
                            Name = "Hayashizaki Jinsuke Shigenobu",
                            Strength = 481
                        },
                        new
                        {
                            Id = 58,
                            Name = "Hayashi Narinaga",
                            Strength = 981
                        },
                        new
                        {
                            Id = 59,
                            Name = "Hijikata Toshizo",
                            Strength = 1264
                        },
                        new
                        {
                            Id = 60,
                            Name = "Hirate Masahide",
                            Strength = 1467
                        },
                        new
                        {
                            Id = 61,
                            Name = "Hitotsubashi Keiki",
                            Strength = 763
                        },
                        new
                        {
                            Id = 62,
                            Name = "Hōjō Masako",
                            Strength = 780
                        },
                        new
                        {
                            Id = 63,
                            Name = "Hōjō Tokimune",
                            Strength = 167
                        },
                        new
                        {
                            Id = 64,
                            Name = "Hōjō Ujiyasu",
                            Strength = 1757
                        },
                        new
                        {
                            Id = 65,
                            Name = "Hōjō Ujimasa",
                            Strength = 695
                        },
                        new
                        {
                            Id = 66,
                            Name = "Honda Tadakatsu",
                            Strength = 1959
                        },
                        new
                        {
                            Id = 67,
                            Name = "Honda Tadatomo",
                            Strength = 1817
                        },
                        new
                        {
                            Id = 68,
                            Name = "Honganji Kennyo",
                            Strength = 1976
                        },
                        new
                        {
                            Id = 69,
                            Name = "Horio Yoshiharu",
                            Strength = 1983
                        },
                        new
                        {
                            Id = 70,
                            Name = "Hosokawa Fujitaka",
                            Strength = 1216
                        },
                        new
                        {
                            Id = 71,
                            Name = "Hosokawa Gracia",
                            Strength = 578
                        },
                        new
                        {
                            Id = 72,
                            Name = "Hosokawa Tadaoki",
                            Strength = 326
                        },
                        new
                        {
                            Id = 73,
                            Name = "Hotta Masatoshi",
                            Strength = 1199
                        },
                        new
                        {
                            Id = 74,
                            Name = "Ii Naoaki",
                            Strength = 230
                        },
                        new
                        {
                            Id = 75,
                            Name = "Ii Naomasa",
                            Strength = 1316
                        },
                        new
                        {
                            Id = 76,
                            Name = "Ii Naomori",
                            Strength = 994
                        },
                        new
                        {
                            Id = 77,
                            Name = "Ii Naonaka",
                            Strength = 1717
                        },
                        new
                        {
                            Id = 78,
                            Name = "Ii Naosuke",
                            Strength = 1133
                        },
                        new
                        {
                            Id = 79,
                            Name = "Ii Naotaka",
                            Strength = 1892
                        },
                        new
                        {
                            Id = 80,
                            Name = "Ii Naotora",
                            Strength = 1895
                        },
                        new
                        {
                            Id = 81,
                            Name = "Ii Naoyuki",
                            Strength = 1721
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ii Naozumi",
                            Strength = 815
                        },
                        new
                        {
                            Id = 83,
                            Name = "Iizasa Ienao",
                            Strength = 1841
                        },
                        new
                        {
                            Id = 84,
                            Name = "Ijuin Tadaaki",
                            Strength = 516
                        },
                        new
                        {
                            Id = 85,
                            Name = "Ikeda Tsuneoki",
                            Strength = 909
                        },
                        new
                        {
                            Id = 86,
                            Name = "Imagawa Ujizane",
                            Strength = 1931
                        },
                        new
                        {
                            Id = 87,
                            Name = "Imagawa Yoshimoto",
                            Strength = 436
                        },
                        new
                        {
                            Id = 88,
                            Name = "Imai Kanehira",
                            Strength = 1279
                        },
                        new
                        {
                            Id = 89,
                            Name = "Inaba Yoshimichi",
                            Strength = 1746
                        },
                        new
                        {
                            Id = 90,
                            Name = "Inugami Nagayasu",
                            Strength = 1107
                        },
                        new
                        {
                            Id = 91,
                            Name = "Ishida Mitsunari",
                            Strength = 368
                        },
                        new
                        {
                            Id = 92,
                            Name = "Isshiki Fujinaga",
                            Strength = 1607
                        },
                        new
                        {
                            Id = 93,
                            Name = "Itagaki Nobukata",
                            Strength = 239
                        },
                        new
                        {
                            Id = 94,
                            Name = "Itō Hirobumi",
                            Strength = 102
                        },
                        new
                        {
                            Id = 95,
                            Name = "Iwanari Tomomichi",
                            Strength = 1000
                        },
                        new
                        {
                            Id = 96,
                            Name = "Jinbo Nagamoto",
                            Strength = 1604
                        },
                        new
                        {
                            Id = 97,
                            Name = "Jonas Tönse",
                            Strength = 494
                        },
                        new
                        {
                            Id = 98,
                            Name = "Kannan Kumar(Salem)",
                            Strength = 1426
                        },
                        new
                        {
                            Id = 99,
                            Name = "Kakeda Toshimune",
                            Strength = 1409
                        },
                        new
                        {
                            Id = 100,
                            Name = "Kaneko Ietada",
                            Strength = 864
                        },
                        new
                        {
                            Id = 101,
                            Name = "Katagiri Katsumoto",
                            Strength = 891
                        },
                        new
                        {
                            Id = 102,
                            Name = "Katakura Kojūro",
                            Strength = 964
                        },
                        new
                        {
                            Id = 103,
                            Name = "Katakura Shigenaga",
                            Strength = 426
                        },
                        new
                        {
                            Id = 104,
                            Name = "Kataoka Mitsumasa",
                            Strength = 1265
                        },
                        new
                        {
                            Id = 105,
                            Name = "Katō Kiyomasa",
                            Strength = 298
                        },
                        new
                        {
                            Id = 106,
                            Name = "Kawakami Gensai",
                            Strength = 250
                        },
                        new
                        {
                            Id = 107,
                            Name = "Kido Takayoshi",
                            Strength = 1410
                        },
                        new
                        {
                            Id = 108,
                            Name = "Kikkawa Hiroie",
                            Strength = 1094
                        },
                        new
                        {
                            Id = 109,
                            Name = "Kimotsuki Kanetsugu",
                            Strength = 1508
                        },
                        new
                        {
                            Id = 110,
                            Name = "Kitamura Kansuke",
                            Strength = 1149
                        },
                        new
                        {
                            Id = 111,
                            Name = "Kobayakawa Hideaki",
                            Strength = 1589
                        },
                        new
                        {
                            Id = 112,
                            Name = "Kobayakawa Hidekane",
                            Strength = 463
                        },
                        new
                        {
                            Id = 113,
                            Name = "Kobayakawa Takakage",
                            Strength = 1675
                        },
                        new
                        {
                            Id = 114,
                            Name = "Konishi Yukinaga",
                            Strength = 1559
                        },
                        new
                        {
                            Id = 115,
                            Name = "Kojima Toyoharu",
                            Strength = 266
                        },
                        new
                        {
                            Id = 116,
                            Name = "Kuroda Kanbei",
                            Strength = 352
                        },
                        new
                        {
                            Id = 117,
                            Name = "Kuroda Kiyotaka",
                            Strength = 297
                        },
                        new
                        {
                            Id = 118,
                            Name = "Kusunoki Masashige",
                            Strength = 30
                        },
                        new
                        {
                            Id = 119,
                            Name = "Kuwana Tarozaemon",
                            Strength = 834
                        },
                        new
                        {
                            Id = 120,
                            Name = "Kumagai Naozane",
                            Strength = 868
                        },
                        new
                        {
                            Id = 121,
                            Name = "Maeda Keiji",
                            Strength = 1716
                        },
                        new
                        {
                            Id = 122,
                            Name = "Maeda Matsu",
                            Strength = 430
                        },
                        new
                        {
                            Id = 123,
                            Name = "Maeda Nagatane",
                            Strength = 434
                        },
                        new
                        {
                            Id = 124,
                            Name = "Maeda Toshiie",
                            Strength = 1032
                        },
                        new
                        {
                            Id = 125,
                            Name = "Maeda Toshinaga",
                            Strength = 603
                        },
                        new
                        {
                            Id = 126,
                            Name = "Maeda Toshitsune",
                            Strength = 54
                        },
                        new
                        {
                            Id = 127,
                            Name = "Magome Kageyu",
                            Strength = 691
                        },
                        new
                        {
                            Id = 128,
                            Name = "Manabe Akifusa",
                            Strength = 691
                        },
                        new
                        {
                            Id = 129,
                            Name = "Matsudaira Katamori",
                            Strength = 1185
                        },
                        new
                        {
                            Id = 130,
                            Name = "Matsudaira Nobutsuna",
                            Strength = 1119
                        },
                        new
                        {
                            Id = 131,
                            Name = "Matsudaira Nobuyasu",
                            Strength = 553
                        },
                        new
                        {
                            Id = 132,
                            Name = "Matsudaira Higo no Kami Katamori",
                            Strength = 1032
                        },
                        new
                        {
                            Id = 133,
                            Name = "Matsudaira Sadanobu",
                            Strength = 1371
                        },
                        new
                        {
                            Id = 134,
                            Name = "Matsudaira Tadayoshi",
                            Strength = 101
                        },
                        new
                        {
                            Id = 135,
                            Name = "Matsudaira Teru",
                            Strength = 1245
                        },
                        new
                        {
                            Id = 136,
                            Name = "Matsunaga Hisahide",
                            Strength = 1400
                        },
                        new
                        {
                            Id = 137,
                            Name = "Matsunaga Hisamichi",
                            Strength = 1338
                        },
                        new
                        {
                            Id = 138,
                            Name = "Matsuo Bashō",
                            Strength = 1763
                        },
                        new
                        {
                            Id = 139,
                            Name = "Matsudaira Motoyasu",
                            Strength = 1433
                        },
                        new
                        {
                            Id = 140,
                            Name = "Minamoto no Mitsunaka",
                            Strength = 1102
                        },
                        new
                        {
                            Id = 141,
                            Name = "Minamoto no Yoshiie",
                            Strength = 1872
                        },
                        new
                        {
                            Id = 142,
                            Name = "Minamoto no Yoshimitsu",
                            Strength = 1203
                        },
                        new
                        {
                            Id = 143,
                            Name = "Minamoto no Yoshinaka",
                            Strength = 817
                        },
                        new
                        {
                            Id = 144,
                            Name = "Minamoto no Yoshitomo",
                            Strength = 1142
                        },
                        new
                        {
                            Id = 145,
                            Name = "Minamoto no Yoshitsune",
                            Strength = 117
                        },
                        new
                        {
                            Id = 146,
                            Name = "Minamoto no Tameyoshi",
                            Strength = 213
                        },
                        new
                        {
                            Id = 147,
                            Name = "Minamoto no Yorimasa",
                            Strength = 1418
                        },
                        new
                        {
                            Id = 148,
                            Name = "Minamoto no Yorimitsu",
                            Strength = 245
                        },
                        new
                        {
                            Id = 149,
                            Name = "Minamoto no Yoritomo",
                            Strength = 1199
                        },
                        new
                        {
                            Id = 150,
                            Name = "Minamoto no Noriyori",
                            Strength = 171
                        },
                        new
                        {
                            Id = 151,
                            Name = "Minoro Takashi",
                            Strength = 1303
                        },
                        new
                        {
                            Id = 152,
                            Name = "Miura Anjin",
                            Strength = 507
                        },
                        new
                        {
                            Id = 153,
                            Name = "Miura Yoshimoto",
                            Strength = 1668
                        },
                        new
                        {
                            Id = 154,
                            Name = "Miyamoto Musashi",
                            Strength = 676
                        },
                        new
                        {
                            Id = 155,
                            Name = "Miyoshi Chōkei",
                            Strength = 12
                        },
                        new
                        {
                            Id = 156,
                            Name = "Miyoshi Kazuhide",
                            Strength = 1437
                        },
                        new
                        {
                            Id = 157,
                            Name = "Miyoshi Masaga",
                            Strength = 1928
                        },
                        new
                        {
                            Id = 158,
                            Name = "Miyoshi Masayasu",
                            Strength = 1002
                        },
                        new
                        {
                            Id = 159,
                            Name = "Miyoshi Moriyata",
                            Strength = 1237
                        },
                        new
                        {
                            Id = 160,
                            Name = "Miyoshi Nagayuki",
                            Strength = 1081
                        },
                        new
                        {
                            Id = 161,
                            Name = "Miyoshi Yoshitsugu",
                            Strength = 994
                        },
                        new
                        {
                            Id = 162,
                            Name = "Mizuno Tadakuni",
                            Strength = 73
                        },
                        new
                        {
                            Id = 163,
                            Name = "Moniwa Yoshinao",
                            Strength = 1315
                        },
                        new
                        {
                            Id = 164,
                            Name = "Mōri Motonari",
                            Strength = 924
                        },
                        new
                        {
                            Id = 165,
                            Name = "Mōri Nagasada",
                            Strength = 1885
                        },
                        new
                        {
                            Id = 166,
                            Name = "Mori Nagayoshi",
                            Strength = 1386
                        },
                        new
                        {
                            Id = 167,
                            Name = "Mōri Okimoto",
                            Strength = 1713
                        },
                        new
                        {
                            Id = 168,
                            Name = "Mori Ranmaru",
                            Strength = 1138
                        },
                        new
                        {
                            Id = 169,
                            Name = "Mōri Takamoto",
                            Strength = 1182
                        },
                        new
                        {
                            Id = 170,
                            Name = "Mori Tadamasa",
                            Strength = 535
                        },
                        new
                        {
                            Id = 171,
                            Name = "Mōri Terumoto",
                            Strength = 1476
                        },
                        new
                        {
                            Id = 172,
                            Name = "Mori Yoshinari",
                            Strength = 1220
                        },
                        new
                        {
                            Id = 173,
                            Name = "Murai Sadakatsu",
                            Strength = 1212
                        },
                        new
                        {
                            Id = 174,
                            Name = "Nagakura Shinpachi",
                            Strength = 1191
                        },
                        new
                        {
                            Id = 175,
                            Name = "Nagao Harukage",
                            Strength = 297
                        },
                        new
                        {
                            Id = 176,
                            Name = "Nagao Kagenobu",
                            Strength = 20
                        },
                        new
                        {
                            Id = 177,
                            Name = "Nagao Masakage",
                            Strength = 1853
                        },
                        new
                        {
                            Id = 178,
                            Name = "Nagao Tamekage",
                            Strength = 576
                        },
                        new
                        {
                            Id = 179,
                            Name = "Nakagawa Kiyohide",
                            Strength = 670
                        },
                        new
                        {
                            Id = 180,
                            Name = "Nakaoka Shintarō",
                            Strength = 1622
                        },
                        new
                        {
                            Id = 181,
                            Name = "Naoe Kagetsuna",
                            Strength = 1190
                        },
                        new
                        {
                            Id = 182,
                            Name = "Naoe Kanetsugu",
                            Strength = 1236
                        },
                        new
                        {
                            Id = 183,
                            Name = "Narita Kaihime",
                            Strength = 612
                        },
                        new
                        {
                            Id = 184,
                            Name = "Nene",
                            Strength = 1189
                        },
                        new
                        {
                            Id = 185,
                            Name = "Nihonmatsu Yoshitsugu",
                            Strength = 334
                        },
                        new
                        {
                            Id = 186,
                            Name = "Niimi Nishiki",
                            Strength = 1651
                        },
                        new
                        {
                            Id = 187,
                            Name = "Niiro Tadamoto",
                            Strength = 1518
                        },
                        new
                        {
                            Id = 188,
                            Name = "Niwa Nagahide",
                            Strength = 210
                        },
                        new
                        {
                            Id = 189,
                            Name = "Niwa Nagashige",
                            Strength = 1768
                        },
                        new
                        {
                            Id = 190,
                            Name = "Oda Hiroyoshi",
                            Strength = 1947
                        },
                        new
                        {
                            Id = 191,
                            Name = "Oda Nobuhide",
                            Strength = 1151
                        },
                        new
                        {
                            Id = 192,
                            Name = "Oda Nobukata",
                            Strength = 1088
                        },
                        new
                        {
                            Id = 193,
                            Name = "Oda Nobukiyo",
                            Strength = 483
                        },
                        new
                        {
                            Id = 194,
                            Name = "Oda Nobunaga",
                            Strength = 1135
                        },
                        new
                        {
                            Id = 195,
                            Name = "Oda Nobutada",
                            Strength = 1238
                        },
                        new
                        {
                            Id = 196,
                            Name = "Oda Nobutomo",
                            Strength = 1486
                        },
                        new
                        {
                            Id = 197,
                            Name = "Oda Nobukatsu",
                            Strength = 765
                        },
                        new
                        {
                            Id = 198,
                            Name = "Oda Nobuyasu",
                            Strength = 188
                        },
                        new
                        {
                            Id = 199,
                            Name = "Ogasawara Shōsai",
                            Strength = 1158
                        },
                        new
                        {
                            Id = 200,
                            Name = "Ōishi Kuranosuke",
                            Strength = 63
                        },
                        new
                        {
                            Id = 201,
                            Name = "Okada Izō",
                            Strength = 14
                        },
                        new
                        {
                            Id = 202,
                            Name = "Judge Ooka",
                            Strength = 1486
                        },
                        new
                        {
                            Id = 203,
                            Name = "Ōta Dōkan",
                            Strength = 297
                        },
                        new
                        {
                            Id = 204,
                            Name = "Ōtani Yoshitsugu",
                            Strength = 1801
                        },
                        new
                        {
                            Id = 205,
                            Name = "Ōtani Yoshiharu",
                            Strength = 1143
                        },
                        new
                        {
                            Id = 206,
                            Name = "Ōtomo Sōrin",
                            Strength = 1640
                        },
                        new
                        {
                            Id = 207,
                            Name = "Okita Sōji",
                            Strength = 124
                        },
                        new
                        {
                            Id = 208,
                            Name = "Ōkubo Toshimichi",
                            Strength = 360
                        },
                        new
                        {
                            Id = 209,
                            Name = "Okunomiya Masaie",
                            Strength = 1430
                        },
                        new
                        {
                            Id = 210,
                            Name = "Ōuchi Yoshitaka",
                            Strength = 952
                        },
                        new
                        {
                            Id = 211,
                            Name = "Omy Yoshika",
                            Strength = 1513
                        },
                        new
                        {
                            Id = 212,
                            Name = "Pore Sufi",
                            Strength = 620
                        },
                        new
                        {
                            Id = 213,
                            Name = "Reizei Takatoyo",
                            Strength = 1158
                        },
                        new
                        {
                            Id = 214,
                            Name = "Rokkaku Sadayori",
                            Strength = 1079
                        },
                        new
                        {
                            Id = 215,
                            Name = "Rokkaku Yoshiharu",
                            Strength = 47
                        },
                        new
                        {
                            Id = 216,
                            Name = "Rokkaku Yoshikata",
                            Strength = 898
                        },
                        new
                        {
                            Id = 217,
                            Name = "Rusu Masakage",
                            Strength = 671
                        },
                        new
                        {
                            Id = 218,
                            Name = "Ryūzōji Takanobu",
                            Strength = 205
                        },
                        new
                        {
                            Id = 219,
                            Name = "Saigo Kiyokazu",
                            Strength = 1652
                        },
                        new
                        {
                            Id = 220,
                            Name = "Saigō Masako",
                            Strength = 455
                        },
                        new
                        {
                            Id = 221,
                            Name = "Sagara Taketō",
                            Strength = 483
                        },
                        new
                        {
                            Id = 222,
                            Name = "Saigō Takamori",
                            Strength = 1530
                        },
                        new
                        {
                            Id = 223,
                            Name = "Saigo Yoshikatsu",
                            Strength = 1071
                        },
                        new
                        {
                            Id = 224,
                            Name = "Saitō Dōsan",
                            Strength = 1465
                        },
                        new
                        {
                            Id = 225,
                            Name = "Saitō Hajime",
                            Strength = 493
                        },
                        new
                        {
                            Id = 226,
                            Name = "Saito Musashibō Benkei",
                            Strength = 129
                        },
                        new
                        {
                            Id = 227,
                            Name = "Saitō Yoshitatsu",
                            Strength = 1198
                        },
                        new
                        {
                            Id = 228,
                            Name = "Sakai Tadakiyo",
                            Strength = 921
                        },
                        new
                        {
                            Id = 229,
                            Name = "Sakai Tadashige",
                            Strength = 86
                        },
                        new
                        {
                            Id = 230,
                            Name = "Sakai Tadatsugu",
                            Strength = 1566
                        },
                        new
                        {
                            Id = 231,
                            Name = "Sakai Tadayo",
                            Strength = 1053
                        },
                        new
                        {
                            Id = 232,
                            Name = "Sakakibara Yasumasa",
                            Strength = 1429
                        },
                        new
                        {
                            Id = 233,
                            Name = "Sakamoto Ryōma",
                            Strength = 47
                        },
                        new
                        {
                            Id = 234,
                            Name = "Sakuma Morimasa",
                            Strength = 1180
                        },
                        new
                        {
                            Id = 235,
                            Name = "Sakuma Nobumori",
                            Strength = 1087
                        },
                        new
                        {
                            Id = 236,
                            Name = "Sanada Akihime",
                            Strength = 1769
                        },
                        new
                        {
                            Id = 237,
                            Name = "Sanada Komatsuhime",
                            Strength = 1206
                        },
                        new
                        {
                            Id = 238,
                            Name = "Sanada Masayuki",
                            Strength = 1053
                        },
                        new
                        {
                            Id = 239,
                            Name = "Sanada Nobuyuki",
                            Strength = 1111
                        },
                        new
                        {
                            Id = 240,
                            Name = "Sanada Yukimura",
                            Strength = 1509
                        },
                        new
                        {
                            Id = 241,
                            Name = "Sasaki Kojirō",
                            Strength = 422
                        },
                        new
                        {
                            Id = 242,
                            Name = "Sassa Narimasa",
                            Strength = 1538
                        },
                        new
                        {
                            Id = 243,
                            Name = "Sasuke Sarutobi",
                            Strength = 1181
                        },
                        new
                        {
                            Id = 244,
                            Name = "Serizawa Kamo",
                            Strength = 1414
                        },
                        new
                        {
                            Id = 245,
                            Name = "Shibata Katsuie",
                            Strength = 1757
                        },
                        new
                        {
                            Id = 246,
                            Name = "Shima Sakon",
                            Strength = 323
                        },
                        new
                        {
                            Id = 247,
                            Name = "Shimada Ichirō",
                            Strength = 1923
                        },
                        new
                        {
                            Id = 248,
                            Name = "Shimazu Katsuhisa",
                            Strength = 479
                        },
                        new
                        {
                            Id = 249,
                            Name = "Shimazu Tadahisa",
                            Strength = 1897
                        },
                        new
                        {
                            Id = 250,
                            Name = "Shimazu Tadatsune",
                            Strength = 1056
                        },
                        new
                        {
                            Id = 251,
                            Name = "Shimazu Tadayoshi",
                            Strength = 728
                        },
                        new
                        {
                            Id = 252,
                            Name = "Shimazu Takahisa",
                            Strength = 414
                        },
                        new
                        {
                            Id = 253,
                            Name = "Shimazu Toyohisa",
                            Strength = 1239
                        },
                        new
                        {
                            Id = 254,
                            Name = "Shimazu Yoshihiro",
                            Strength = 236
                        },
                        new
                        {
                            Id = 255,
                            Name = "Shimazu Yoshihisa",
                            Strength = 440
                        },
                        new
                        {
                            Id = 256,
                            Name = "Shindou Hiroshii",
                            Strength = 1549
                        },
                        new
                        {
                            Id = 257,
                            Name = "Sogo Nagayasu",
                            Strength = 1328
                        },
                        new
                        {
                            Id = 258,
                            Name = "Sue Yoshitaka",
                            Strength = 1883
                        },
                        new
                        {
                            Id = 259,
                            Name = "Tachibana Muneshige",
                            Strength = 1104
                        },
                        new
                        {
                            Id = 260,
                            Name = "Tachibana Dōsetsu",
                            Strength = 668
                        },
                        new
                        {
                            Id = 261,
                            Name = "Tachibana Ginchiyo",
                            Strength = 483
                        },
                        new
                        {
                            Id = 262,
                            Name = "Taigen Sessai",
                            Strength = 618
                        },
                        new
                        {
                            Id = 263,
                            Name = "Taira no Kiyomori",
                            Strength = 1131
                        },
                        new
                        {
                            Id = 264,
                            Name = "Taira Masakado",
                            Strength = 1634
                        },
                        new
                        {
                            Id = 265,
                            Name = "Takahashi Shigetane",
                            Strength = 227
                        },
                        new
                        {
                            Id = 266,
                            Name = "Takenaka Shigeharu",
                            Strength = 976
                        },
                        new
                        {
                            Id = 267,
                            Name = "Takasugi Shinsaku",
                            Strength = 327
                        },
                        new
                        {
                            Id = 268,
                            Name = "Takayama Justo",
                            Strength = 1689
                        },
                        new
                        {
                            Id = 269,
                            Name = "Takayama Ukon",
                            Strength = 240
                        },
                        new
                        {
                            Id = 270,
                            Name = "Takechi Hanpeita",
                            Strength = 1404
                        },
                        new
                        {
                            Id = 271,
                            Name = "Takeda Katsuyori",
                            Strength = 1485
                        },
                        new
                        {
                            Id = 272,
                            Name = "Takeda Nobukatsu",
                            Strength = 1018
                        },
                        new
                        {
                            Id = 273,
                            Name = "Takeda Nobushige",
                            Strength = 576
                        },
                        new
                        {
                            Id = 274,
                            Name = "Takeda Shingen",
                            Strength = 72
                        },
                        new
                        {
                            Id = 275,
                            Name = "Takenaka Hanbei",
                            Strength = 1143
                        },
                        new
                        {
                            Id = 276,
                            Name = "Tani Tadasumi",
                            Strength = 622
                        },
                        new
                        {
                            Id = 277,
                            Name = "Tōdō Takatora",
                            Strength = 1195
                        },
                        new
                        {
                            Id = 278,
                            Name = "Toki Yorinari",
                            Strength = 1883
                        },
                        new
                        {
                            Id = 279,
                            Name = "Tochimitsu Gantyoki",
                            Strength = 972
                        },
                        new
                        {
                            Id = 280,
                            Name = "Tokugawa Ieyasu",
                            Strength = 1379
                        },
                        new
                        {
                            Id = 281,
                            Name = "Tokugawa Hidetada",
                            Strength = 903
                        },
                        new
                        {
                            Id = 282,
                            Name = "Tokugawa Nariaki",
                            Strength = 315
                        },
                        new
                        {
                            Id = 283,
                            Name = "Tokugawa Yoshinobu",
                            Strength = 360
                        },
                        new
                        {
                            Id = 284,
                            Name = "Torii Mototada",
                            Strength = 1023
                        },
                        new
                        {
                            Id = 285,
                            Name = "Toyotomi Hidenaga",
                            Strength = 715
                        },
                        new
                        {
                            Id = 286,
                            Name = "Toyotomi Hideyoshi",
                            Strength = 915
                        },
                        new
                        {
                            Id = 287,
                            Name = "Toyotomi Hideyori",
                            Strength = 861
                        },
                        new
                        {
                            Id = 288,
                            Name = "Tozuka Tadaharu",
                            Strength = 858
                        },
                        new
                        {
                            Id = 289,
                            Name = "Tsukahara Bokuden",
                            Strength = 1646
                        },
                        new
                        {
                            Id = 290,
                            Name = "Uesugi Kagekatsu",
                            Strength = 1900
                        },
                        new
                        {
                            Id = 291,
                            Name = "Uesugi Kagetora",
                            Strength = 1812
                        },
                        new
                        {
                            Id = 292,
                            Name = "Uesugi Kenshin",
                            Strength = 1401
                        },
                        new
                        {
                            Id = 293,
                            Name = "Ujiie Naotomo",
                            Strength = 965
                        },
                        new
                        {
                            Id = 294,
                            Name = "Ukita Naoie",
                            Strength = 1067
                        },
                        new
                        {
                            Id = 295,
                            Name = "Ukita Okiie",
                            Strength = 1082
                        },
                        new
                        {
                            Id = 296,
                            Name = "Umezawa Michiharu",
                            Strength = 1308
                        },
                        new
                        {
                            Id = 297,
                            Name = "Usami Sadamitsu",
                            Strength = 1554
                        },
                        new
                        {
                            Id = 298,
                            Name = "Uyama Hisanobu",
                            Strength = 466
                        },
                        new
                        {
                            Id = 299,
                            Name = "Wada Shinsuke",
                            Strength = 405
                        },
                        new
                        {
                            Id = 300,
                            Name = "Watanabe Kazan",
                            Strength = 781
                        },
                        new
                        {
                            Id = 301,
                            Name = "Watanabe no Tsuna",
                            Strength = 923
                        },
                        new
                        {
                            Id = 302,
                            Name = "Yasumero Kenshin",
                            Strength = 1939
                        },
                        new
                        {
                            Id = 303,
                            Name = "Yagyū Jūbei Mitsuyoshi",
                            Strength = 106
                        },
                        new
                        {
                            Id = 304,
                            Name = "Yagyū Munenori",
                            Strength = 714
                        },
                        new
                        {
                            Id = 305,
                            Name = "Yamauchi Kazutoyo",
                            Strength = 654
                        },
                        new
                        {
                            Id = 306,
                            Name = "Yamada Arinaga",
                            Strength = 471
                        },
                        new
                        {
                            Id = 307,
                            Name = "Yamada Arinobu",
                            Strength = 1192
                        },
                        new
                        {
                            Id = 308,
                            Name = "Yamada Nagamasa",
                            Strength = 366
                        },
                        new
                        {
                            Id = 309,
                            Name = "Yamagata Masakage",
                            Strength = 387
                        },
                        new
                        {
                            Id = 310,
                            Name = "Yamakawa Hiroshi",
                            Strength = 1720
                        },
                        new
                        {
                            Id = 311,
                            Name = "Yamakawa Kenjirō",
                            Strength = 1568
                        },
                        new
                        {
                            Id = 312,
                            Name = "Yamakawa Naoe",
                            Strength = 1665
                        },
                        new
                        {
                            Id = 313,
                            Name = "Yamanaka Yukimori",
                            Strength = 1182
                        },
                        new
                        {
                            Id = 314,
                            Name = "Yamanami Keisuke",
                            Strength = 1687
                        },
                        new
                        {
                            Id = 315,
                            Name = "Yamaoka Tesshū",
                            Strength = 1909
                        },
                        new
                        {
                            Id = 316,
                            Name = "Yanagawa Kenzaburo",
                            Strength = 1796
                        },
                        new
                        {
                            Id = 317,
                            Name = "Yanagisawa Yoshiyasu",
                            Strength = 57
                        },
                        new
                        {
                            Id = 318,
                            Name = "Yonekura Shigetsugu",
                            Strength = 688
                        },
                        new
                        {
                            Id = 319,
                            Name = "Yūki Hideyasu",
                            Strength = 958
                        },
                        new
                        {
                            Id = 320,
                            Name = "Yasuke",
                            Strength = 736
                        });
                });

            modelBuilder.Entity("Dojo.Domain.Entities.Samourai", b =>
                {
                    b.HasOne("Dojo.Domain.Entities.Arme", "Arme")
                        .WithMany()
                        .HasForeignKey("ArmeId");

                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
